from customtkinter import *

class Keyboard(CTkFrame):
    def __init__ (self, parent: object) -> None:
        super().__init__(master=parent, fg_color="transparent")
        
        Upper_Button_Frame = CTkFrame(self, fg_color="transparent")
        Upper_Button_Frame.pack(pady=(10, 5))
        
        btn_a = CTkButton(Upper_Button_Frame, text="A", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_a))
        btn_a.pack(side="left", padx=5)
        btn_a.bind("<Enter>", lambda e: self.on_hover(btn_a, e))
        btn_a.bind("<Leave>", lambda e: self.off_hover(btn_a))
        btn_b = CTkButton(Upper_Button_Frame, text="B", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_b))
        btn_b.pack(side="left", padx=5)
        btn_b.bind("<Enter>", lambda e: self.on_hover(btn_b))
        btn_b.bind("<Leave>", lambda e: self.off_hover(btn_b))
        btn_c = CTkButton(Upper_Button_Frame, text="C", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_c))
        btn_c.pack(side="left", padx=5)
        btn_c.bind("<Enter>", lambda e: self.on_hover(btn_c))
        btn_c.bind("<Leave>", lambda e: self.off_hover(btn_c))
        btn_d = CTkButton(Upper_Button_Frame, text="D", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_d))
        btn_d.pack(side="left", padx=5)
        btn_d.bind("<Enter>", lambda e: self.on_hover(btn_d))
        btn_d.bind("<Leave>", lambda e: self.off_hover(btn_d))
        btn_e = CTkButton(Upper_Button_Frame, text="E", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_e))
        btn_e.pack(side="left", padx=5)
        btn_e.bind("<Enter>", lambda e: self.on_hover(btn_e))
        btn_e.bind("<Leave>", lambda e: self.off_hover(btn_e))
        btn_f = CTkButton(Upper_Button_Frame, text="F", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_f))
        btn_f.pack(side="left", padx=5)
        btn_f.bind("<Enter>", lambda e: self.on_hover(btn_f))
        btn_f.bind("<Leave>", lambda e: self.off_hover(btn_f))
        btn_g = CTkButton(Upper_Button_Frame, text="G", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_g))
        btn_g.pack(side="left", padx=5)
        btn_g.bind("<Enter>", lambda e: self.on_hover(btn_g))
        btn_g.bind("<Leave>", lambda e: self.off_hover(btn_g))
        btn_h = CTkButton(Upper_Button_Frame, text="H", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_h))
        btn_h.pack(side="left", padx=5)
        btn_h.bind("<Enter>", lambda e: self.on_hover(btn_h))
        btn_h.bind("<Leave>", lambda e: self.off_hover(btn_h))
        btn_i = CTkButton(Upper_Button_Frame, text="I", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_i))
        btn_i.pack(side="left", padx=5)
        btn_i.bind("<Enter>", lambda e: self.on_hover(btn_i))
        btn_i.bind("<Leave>", lambda e: self.off_hover(btn_i))
        btn_j = CTkButton(Upper_Button_Frame, text="J", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_j))
        btn_j.pack(side="left", padx=5)
        btn_j.bind("<Enter>", lambda e: self.on_hover(btn_j))
        btn_j.bind("<Leave>", lambda e: self.off_hover(btn_j))
        btn_k = CTkButton(Upper_Button_Frame, text="K", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_k))
        btn_k.pack(side="left", padx=5)
        btn_k.bind("<Enter>", lambda e: self.on_hover(btn_k))
        btn_k.bind("<Leave>", lambda e: self.off_hover(btn_k))
        btn_l = CTkButton(Upper_Button_Frame, text="L", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_l))
        btn_l.pack(side="left", padx=5)
        btn_l.bind("<Enter>", lambda e: self.on_hover(btn_l))
        btn_l.bind("<Leave>", lambda e: self.off_hover(btn_l))
        btn_m = CTkButton(Upper_Button_Frame, text="M", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_m))
        btn_m.pack(side="left", padx=5)
        btn_m.bind("<Enter>", lambda e: self.on_hover(btn_m))
        btn_m.bind("<Leave>", lambda e: self.off_hover(btn_m))

        Lower_Button_Frame = CTkFrame(self, fg_color="transparent")
        Lower_Button_Frame.pack(pady=(5, 10))
        btn_n = CTkButton(Lower_Button_Frame, text="N", width=50).pack(side="left", padx=5)
        btn_o = CTkButton(Lower_Button_Frame, text="O", width=50).pack(side="left", padx=5)
        btn_p = CTkButton(Lower_Button_Frame, text="P", width=50).pack(side="left", padx=5)
        btn_q = CTkButton(Lower_Button_Frame, text="Q", width=50).pack(side="left", padx=5)
        btn_r = CTkButton(Lower_Button_Frame, text="R", width=50).pack(side="left", padx=5)
        btn_s = CTkButton(Lower_Button_Frame, text="S", width=50).pack(side="left", padx=5)
        btn_t = CTkButton(Lower_Button_Frame, text="T", width=50).pack(side="left", padx=5)
        btn_u = CTkButton(Lower_Button_Frame, text="U", width=50).pack(side="left", padx=5)
        btn_v = CTkButton(Lower_Button_Frame, text="V", width=50).pack(side="left", padx=5)
        btn_w = CTkButton(Lower_Button_Frame, text="W", width=50).pack(side="left", padx=5)
        btn_x = CTkButton(Lower_Button_Frame, text="X", width=50).pack(side="left", padx=5)
        btn_y = CTkButton(Lower_Button_Frame, text="Y", width=50).pack(side="left", padx=5)
        btn_z = CTkButton(Lower_Button_Frame, text="Z", width=50).pack(side="left", padx=5)
        
    def on_hover(self, btn: object, event=None) -> None:
        btn.configure(text_color="#350a66")
        btn.configure(fg_color="#e757bc")
        event.widget.configure(cursor="hand2")
        
    def off_hover(self, btn: object) -> None:
        btn.configure(text_color="#FFFFFF")
        btn.configure(fg_color="#520CA1")
        
    def clicked(self, btn: object) -> None:
        btn.unbind("<Enter>")
        btn.unbind("<Leave>")
        btn.configure(state="disabled")
        btn.configure(fg_color="#2f1947")
        btn.configure(text_color="#7A7381")
        
        # if wrong key
        btn.configure(border_width=1)
        btn.configure(border_color="red")