from customtkinter import *

class Keyboard(CTkFrame):
    def __init__ (self, parent: object) -> None:
        super().__init__(master=parent, fg_color="transparent")
        
        Upper_Button_Frame = CTkFrame(self, fg_color="transparent")
        Upper_Button_Frame.pack(pady=(10, 5))
        
        btn_a = CTkButton(Upper_Button_Frame, text="A", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_a))
        btn_a.pack(side="left", padx=5)
        btn_a.bind("<Enter>", lambda e: self.on_hover(btn_a, e))
        btn_a.bind("<Leave>", lambda e: self.off_hover(btn_a, e))
        btn_b = CTkButton(Upper_Button_Frame, text="B", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_b))
        btn_b.pack(side="left", padx=5)
        btn_b.bind("<Enter>", lambda e: self.on_hover(btn_b, e))
        btn_b.bind("<Leave>", lambda e: self.off_hover(btn_b, e))
        btn_c = CTkButton(Upper_Button_Frame, text="C", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_c))
        btn_c.pack(side="left", padx=5)
        btn_c.bind("<Enter>", lambda e: self.on_hover(btn_c, e))
        btn_c.bind("<Leave>", lambda e: self.off_hover(btn_c, e))
        btn_d = CTkButton(Upper_Button_Frame, text="D", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_d))
        btn_d.pack(side="left", padx=5)
        btn_d.bind("<Enter>", lambda e: self.on_hover(btn_d, e))
        btn_d.bind("<Leave>", lambda e: self.off_hover(btn_d, e))
        btn_e = CTkButton(Upper_Button_Frame, text="E", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_e))
        btn_e.pack(side="left", padx=5)
        btn_e.bind("<Enter>", lambda e: self.on_hover(btn_e, e))
        btn_e.bind("<Leave>", lambda e: self.off_hover(btn_e, e))
        btn_f = CTkButton(Upper_Button_Frame, text="F", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_f))
        btn_f.pack(side="left", padx=5)
        btn_f.bind("<Enter>", lambda e: self.on_hover(btn_f, e))
        btn_f.bind("<Leave>", lambda e: self.off_hover(btn_f, e))
        btn_g = CTkButton(Upper_Button_Frame, text="G", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_g))
        btn_g.pack(side="left", padx=5)
        btn_g.bind("<Enter>", lambda e: self.on_hover(btn_g, e))
        btn_g.bind("<Leave>", lambda e: self.off_hover(btn_g, e))
        btn_h = CTkButton(Upper_Button_Frame, text="H", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_h))
        btn_h.pack(side="left", padx=5)
        btn_h.bind("<Enter>", lambda e: self.on_hover(btn_h, e))
        btn_h.bind("<Leave>", lambda e: self.off_hover(btn_h, e))
        btn_i = CTkButton(Upper_Button_Frame, text="I", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_i))
        btn_i.pack(side="left", padx=5)
        btn_i.bind("<Enter>", lambda e: self.on_hover(btn_i, e))
        btn_i.bind("<Leave>", lambda e: self.off_hover(btn_i, e))
        btn_j = CTkButton(Upper_Button_Frame, text="J", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_j))
        btn_j.pack(side="left", padx=5)
        btn_j.bind("<Enter>", lambda e: self.on_hover(btn_j, e))
        btn_j.bind("<Leave>", lambda e: self.off_hover(btn_j, e))
        btn_k = CTkButton(Upper_Button_Frame, text="K", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_k))
        btn_k.pack(side="left", padx=5)
        btn_k.bind("<Enter>", lambda e: self.on_hover(btn_k, e))
        btn_k.bind("<Leave>", lambda e: self.off_hover(btn_k, e))
        btn_l = CTkButton(Upper_Button_Frame, text="L", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_l))
        btn_l.pack(side="left", padx=5)
        btn_l.bind("<Enter>", lambda e: self.on_hover(btn_l, e))
        btn_l.bind("<Leave>", lambda e: self.off_hover(btn_l, e))
        btn_m = CTkButton(Upper_Button_Frame, text="M", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_m))
        btn_m.pack(side="left", padx=5)
        btn_m.bind("<Enter>", lambda e: self.on_hover(btn_m, e))
        btn_m.bind("<Leave>", lambda e: self.off_hover(btn_m, e))
        

        Lower_Button_Frame = CTkFrame(self, fg_color="transparent")
        Lower_Button_Frame.pack(pady=(5, 10))
        
        btn_n = CTkButton(Lower_Button_Frame, text="N", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_n))
        btn_n.pack(side="left", padx=5)
        btn_n.bind("<Enter>", lambda e: self.on_hover(btn_n, e))
        btn_n.bind("<Leave>", lambda e: self.off_hover(btn_n, e))
        btn_o = CTkButton(Lower_Button_Frame, text="O", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_o))
        btn_o.pack(side="left", padx=5)
        btn_o.bind("<Enter>", lambda e: self.on_hover(btn_o, e))
        btn_o.bind("<Leave>", lambda e: self.off_hover(btn_o, e))
        btn_p = CTkButton(Lower_Button_Frame, text="P", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_p))
        btn_p.pack(side="left", padx=5)
        btn_p.bind("<Enter>", lambda e: self.on_hover(btn_p, e))
        btn_p.bind("<Leave>", lambda e: self.off_hover(btn_p, e))
        btn_q = CTkButton(Lower_Button_Frame, text="Q", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_q))
        btn_q.pack(side="left", padx=5)
        btn_q.bind("<Enter>", lambda e: self.on_hover(btn_q, e))
        btn_q.bind("<Leave>", lambda e: self.off_hover(btn_q, e))
        btn_r = CTkButton(Lower_Button_Frame, text="R", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_r))
        btn_r.pack(side="left", padx=5)
        btn_r.bind("<Enter>", lambda e: self.on_hover(btn_r, e))
        btn_r.bind("<Leave>", lambda e: self.off_hover(btn_r, e))
        btn_s = CTkButton(Lower_Button_Frame, text="S", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_s))
        btn_s.pack(side="left", padx=5)
        btn_s.bind("<Enter>", lambda e: self.on_hover(btn_s, e))
        btn_s.bind("<Leave>", lambda e: self.off_hover(btn_s, e))
        btn_t = CTkButton(Lower_Button_Frame, text="T", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_t))
        btn_t.pack(side="left", padx=5)
        btn_t.bind("<Enter>", lambda e: self.on_hover(btn_t, e))
        btn_t.bind("<Leave>", lambda e: self.off_hover(btn_t, e))
        btn_u = CTkButton(Lower_Button_Frame, text="U", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_u))
        btn_u.pack(side="left", padx=5)
        btn_u.bind("<Enter>", lambda e: self.on_hover(btn_u, e))
        btn_u.bind("<Leave>", lambda e: self.off_hover(btn_u, e))
        btn_v = CTkButton(Lower_Button_Frame, text="V", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_v))
        btn_v.pack(side="left", padx=5)
        btn_v.bind("<Enter>", lambda e: self.on_hover(btn_v, e))
        btn_v.bind("<Leave>", lambda e: self.off_hover(btn_v, e))
        btn_w = CTkButton(Lower_Button_Frame, text="W", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_w))
        btn_w.pack(side="left", padx=5)
        btn_w.bind("<Enter>", lambda e: self.on_hover(btn_w, e))
        btn_w.bind("<Leave>", lambda e: self.off_hover(btn_w, e))
        btn_x = CTkButton(Lower_Button_Frame, text="X", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_x))
        btn_x.pack(side="left", padx=5)
        btn_x.bind("<Enter>", lambda e: self.on_hover(btn_x, e))
        btn_x.bind("<Leave>", lambda e: self.off_hover(btn_x, e))
        btn_y = CTkButton(Lower_Button_Frame, text="Y", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_y))
        btn_y.pack(side="left", padx=5)
        btn_y.bind("<Enter>", lambda e: self.on_hover(btn_y, e))
        btn_y.bind("<Leave>", lambda e: self.off_hover(btn_y, e))
        btn_z = CTkButton(Lower_Button_Frame, text="Z", width=70, height=40, fg_color="#520CA1", corner_radius=5, text_color="#FFFFFF", font=("Arial", -16, "bold"), command=lambda: self.clicked(btn_z))
        btn_z.pack(side="left", padx=5)
        btn_z.bind("<Enter>", lambda e: self.on_hover(btn_z, e))
        btn_z.bind("<Leave>", lambda e: self.off_hover(btn_z, e))
        
    def on_hover(self, btn: object, event) -> None:
        btn.configure(text_color="#350a66")
        btn.configure(fg_color="#e757bc")
        event.widget.configure(cursor="hand2")
        
    def off_hover(self, btn: object, event) -> None:
        btn.configure(text_color="#FFFFFF")
        btn.configure(fg_color="#520CA1")
        event.widget.configure(cursor="")
        
    def clicked(self, btn: object) -> None:
        btn.unbind("<Enter>")
        btn.unbind("<Leave>")
        btn.configure(state="disabled")
        btn.configure(fg_color="#2f1947")
        btn.configure(text_color="#7A7381")
        
        # if wrong key
        btn.configure(border_width=1)
        btn.configure(border_color="red")